[project]
name = "lista-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clipspy>=1.0.5",
    "pdfplumber>=0.11.7",
]
